title: "PAPPL Scanning Documentation"
description: "Complete Documentation for the PAPPL Scanning Workflow."

remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs
url: "https://kappuccino111.github.io"
baseurl: "/ScanningDocs"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-mentions